pipeline:
  build: 
    image: registry.cn-hangzhou.aliyuncs.com/acs/maven
    commands:
      - mvn clean package -DskipTests
    volumes:
      - /root/maven/repository:/root/.m2/repository
      - /root/maven/settings.xml:/usr/share/maven/conf/settings.xml
  
  publish:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: registry.cn-shenzhen.aliyuncs.com/pipipan/meetingroom
    tags: latest