pipeline:
  build: 
    image: registry.cn-hangzhou.aliyuncs.com/acs/maven
    commands:
      - mvn clean package -DskipTests
    volumes:
      - /root/maven/repository:/usr/share/maven/ref
      - /root/maven/settings.xml:/usr/share/maven/conf/settings.xml